name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@v2
       - uses: pnpm/action-setup@v2
       - uses: actions/setup-node@v2
         with:
           node-version: '18'
           cache: 'pnpm'
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - run: pnpm install
      - run: pnpx tsc --noEmit
      - run: pnpm run build

      - run: mkdir dist
      - run: cp -r example ./dist
      - run: cp -r cjs ./dist
      - run: cp -r esm ./dist
      - run: cp -r umd ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
