name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - run: npm ci
      - run: npx tsc --noEmit
      - run: npm run lint
      - run: npm test
