name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - run: pnpm install
      - run: npx tsc --noEmit
      - run: pnpm run lint
      - run: pnpm test
