name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - name: Install and Test
        run: npm cit
      - name: Linter
        run: npm run lint
      - name: Publish to GitHub Package (unstable)
        if: "!startswith(github.event, 'pull_request')"
        run: ./scripts/publish-to-github.sh
