name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js (LTS)
        uses: actions/setup-node@v2-beta
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - name: Install and Test
        run: npm cit
      - name: Linter
        run: npm run lint
      - name: Publish to GitHub Package (unstable)
        run: |
          VERSION=$(jq -r '.version' package.json)
          npm --no-git-tag-version version "$VERSION-$BUILD_VERSION"
          npm publish
